# -*- coding: utf-8 -*-
"""GIS---GEOGRAPHIC INFORMATION SYSTEMS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EvBXGJTzs6mhyiU_6EYU6iq8-u7fzTOY

# GIS---GEOGRAPHIC INFORMATION SYSTEMS
"""

#%pip install -U leafmap

# Commented out IPython magic to ensure Python compatibility.
# %pip install rasterio

pip install geopandas

import leafmap

m = leafmap.Map()
m.add_basemap("HYBRID")
m

m.to_html("my_map.html")

m.add_basemap("TERRAIN")
m

img1 = "https://open.gishub.org/data/images/berkeley.jpg"
img2 = "https://open.gishub.org/data/images/berkeley_sam.jpg"
leafmap.image_comparison(
    img1,
    img2,
    label1="Satellite Image",
    label2="Image Segmentation",
    starting_position=50,
    out_html="image_comparison.html",
)

import geopandas as gpd

gpd = gpd.read_file("https://github.com/opengeos/leafmap/raw/master/examples/data/cable_geo.geojson")

m = leafmap.Map()
m.add_gdf(gpd, layer_name="Cable lines")
m

import plotly.graph_objects as go
from plotly.offline import init_notebook_mode, iplot,plot
init_notebook_mode(connected=True)

import pandas as pd

df = pd.read_csv("/content/2014_World_Power_Consumption (1)")
df.head()

import plotly.graph_objects as go
from plotly.offline import init_notebook_mode, iplot,plot
init_notebook_mode(connected=True)

data=dict(
    type="choropleth",
    colorscale='Viridis',
    reversescale=True,
    locations=df["Country"],
    locationmode="country names",
    z=df["Power Consumption KWH"],
    text=df["Country"],
    colorbar={'title':"World Power Consunmption"}
)
layout=dict(title="World Power Consunmption",
            geo=dict(showframe=False,projection={'type':'mercator'})
            )

choromap=go.Figure(data=data,layout=layout)
iplot(choromap,validate=False)

